### ISSUE TITLE
GMapCluster - "Error: setMaxZoom is not a method of....."

### ISSUE THREAD

**Issue by tahaipek** [fawmi/vue-google-maps#149]
I'm trying sample [MapCluster](https://github.com/fawmi/vue-google-maps#cluster) with version **"@fawmi/vue-google-maps": "^0.9.79** and I'm getting the following error.

Any idea about this error and warning?

```

bindProps.js:32 Uncaught (in promise) Error: setMaxZoom is not a method of (the Maps object corresponding to) undefined
    at bindProps (bindProps.js:32:13)
    at build-component.js:108:11

```
![Screenshot 2022-09-02 102119](https://user-images.githubusercontent.com/5754670/188081353-a1f4a150-37b0-4ab9-a395-c73718e6ca1b.png)

**Comment by tahaipek** [comment]
It looks like a bug from the current version. I downgraded the package version. _("@fawmi/vue-google-maps": "0.9.72" )_

In this version _("0.9.72")_ , methods that are deprecated by Google Map Api are displayed as warnings.
```
google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead: https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener
The feature will continue to work and there is no plan to decommission it.
```

**Comment by terryarden** [comment]
When will a new version be released that fixes this issue? When I roll back to 0.9.72, the above error is fixed but the cluster icons (eg., m1.png, etc) is no longer found. 
<img width="844" alt="Screen Shot 2022-10-05 at 1 20 03 PM" src="https://user-images.githubusercontent.com/68717760/194155504-78ad8e93-5acc-4f8c-908d-b976cc4af222.png">

**Comment by lugrinder** [comment]
Same issue, please fix. All works fine, except when adding cluster.
