### ISSUE TITLE
Clustering issue.

### ISSUE THREAD

**Issue by YassineChe** [fawmi/vue-google-maps#160]
Hello,

Having an issue with clustering `GMapCluster`
Trying to cluster markers but its doesn't seem to work
here a snapshot of my console

```
bindProps.js?v=08c62b4d:32 Uncaught (in promise) Error: setMaxZoom is not a method of (the Maps object corresponding to) undefined
    at bindProps (bindProps.js?v=08c62b4d:32:13)
    at build-component.js?v=08c62b4d:108:11
```

And 

```
cluster.vue:101 Uncaught (in promise) TypeError: this.$clusterObject.repaint is not a function
    at Proxy.updated (cluster.vue:101:27)
    at runtime-core.esm-bundler.js:2723:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2697:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:341:32)
    at flushJobs (runtime-core.esm-bundler.js:395:9)
```

I tried some solutions from opened issues in here and still won't to work, i tried also to downgrade the version, and the same thing.

Thanks.

**Comment by sasaorasanin** [comment]
Why is this closed since its issue still?

**Comment by YassineChe** [comment]
Hey,

Use this instead: 
https://www.npmjs.com/package/vue-google-maps-community-fork
